# Generated by Django 3.0.2 on 2020-01-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='ico',
            new_name='icon',
        ),
    ]
