# Generated by Django 3.0.2 on 2020-01-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200130_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='longitude',
            new_name='lon',
        ),
    ]
