# Generated by Django 3.0.2 on 2020-01-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200130_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='sky',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_deg',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(default=None),
        ),
    ]
