# Generated by Django 3.0.2 on 2020-01-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_weather_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='tepm',
            field=models.FloatField(default=None),
        ),
    ]
