# Generated by Django 3.0.2 on 2020-01-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200130_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tepm',
            field=models.FloatField(default=0),
        ),
    ]
