# Generated by Django 3.0.2 on 2020-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200130_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='tepm',
        ),
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.FloatField(default=1),
        ),
    ]
